on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    branches:
    - main

jobs:
  my_job:
    name: speak
    runs-on: ubuntu-latest

    steps:
    - name: echo
      shell: bash
      run: echo $"Workflows running..."

  my_job:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run-pytest
      run: |
        pip install pytest pytest-cov
        pytest test_api.py

    my_job:
      name: lint
      runs-on: ubuntu-latest
  
      steps:
    - name: checkout
      uses: actions/checkout@v4
  
    - name: install-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
  
    - name: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: lint
      if: '!cancelled()'
      run: pylint --fail-under=8 ./*.py
    
