on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    branches:
    - main

jobs:
  my_job:
    name: speak
    runs-on: ubuntu-latest

    steps:
    - name: echo
      shell: bash
      run: echo "Workflows running..."

  my_job:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: 
    
    
